### ISSUE TITLE
Explanations should be returned as a list and not a data.frame

### ISSUE THREAD

**Issue by pommedeterresautee** [thomasp85/lime#16]
Several columns content are repeated on each row for a given case. The format of the result data is not adapted to the content of the explanations.
Instead, we should return a nested list:
- each is represented by a slot in the list
- each slot is a list itself containing several slots:
  - a data.frame with information related to the selected features (feature name, description, weight, ...)
  - a scalar with label_prob
  - model type
  - model intercept
  - data
  - prediction

Would improve readability of the explanations in a natural way (because the representation would look like what it means) and would be easy to implement the modification without breaking everything.
Let me know if you want me to PR that.

**Comment by thomasp85** [comment]
I'm all for optimising the output, but I'm not positive about the idea of returning a list instead of a data.frame. When we are closer to a final API for tabular and text explanations we can have a look at which information is shared and which is specific to the explanation and proceed from there.

List of lists are very user hostile IMO as it makes it annoying to work with downstream (e.g. extracting a slot piece of information will require a `map`/`sapply` instead of a `$`)

**Comment by pommedeterresautee** [comment]
Makes sense. Let's wait stabilisation of the code (and return type) then we may try to think to a better presentation of the result (may be an indication in the column names? or just some documentation ?). I close for now.

**Comment by iron0012** [comment]
Just wanted to say that I really appreciate that the explanations are provided in data frame format, for exactly the reasons that @thomasp85 described. I find myself viewing the explanations data frame often while using (and troubleshooting) LIME, and it would be much more difficult to do so if they were in a list or other more "opaque" format.
