### ISSUE TITLE
R vs Python Implementations

### ISSUE THREAD

**Issue by goodekat** [thomasp85/lime#81]
Hi Thomas, 

Thank you for writing this wonderful package! I have a question about how the performance of the R and Python implementations of LIME compare. You mention that the R package is not a “line-by-line” implementation of the Python version, but it follows the same ideas. Since the R version is not an exact replicate of the Python version, I’m curious to know if there are differences between the two. Have you done any work to look into how similar the results are from the two implementations? If you have, could you share your findings?

Thank you!

**Comment by thomasp85** [comment]
There are a couple of differences.

- The python and r version uses different implementations for ridge regression for obvious reasons - there might be numerical differences there
- The new R version now uses gower distance by default for tabular data - this is IMO a much better approach than euclidean + an exponential kernel
- The new R version samples numerical features from a kernel density estimation rather than expecting them to follow a gaussian distribution - this should result in permuted tabular data much better resembling the training data
- Image input are permuted using slic instead of quickshift segmentation in the r version. Further the r version allows much more control over the image permutation process.

I have not run any formal tests between the two, mainly because I dislike doing data analysis in Python, but judging from feedback and what I can see from the Python lime tutorials the two implementations are alligned pretty well

**Comment by goodekat** [comment]
Sounds good. Thanks for sharing your thoughts on this!
